Input1 = int(input("Enter your number: "))
Input2 = int(input("Enter your second number: "))
print(f"{Input1} + {Input2} = {Input1 + Input2}")
print(f"{Input1} - {Input2} = {Input1 - Input2}")
print(f"{Input1} * {Input2} = {Input1 * Input2}")
print(f"{Input1} / {Input2} = {Input1 / Input2}")
print(f"{Input1} % {Input2} = {Input1 % Input2}")
print(f"{Input1} // {Input2} = {Input1 // Input2}")
print(f"{Input1} ** {Input2} = {Input1 ** Input2}")

